#version: '3.8'
#Docker Compose V2ではversion:が不要となった。

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: komadorihouse_development
      #MYSQL_USER: root
      #MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
  
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://root:password@db:3306/komadorihouse_development
